version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: sociallife
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - sociallife-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/sociallife
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - api.security.token.secret=social_secret
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - sociallife-network

networks:
  sociallife-network:
    driver: bridge
